# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 3

# Personal info
name: Franco Silva
title: Solution Engineering Intern @ FICO
email: franco.silva4477@alumnos.udg.mx
website: https://github.com/franco-e-s-c

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: Franco_e_s_c
github_username:  franco-e-s-c
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: Franco Silva
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jfif
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Franco currently I'm working at FICO as a Solution Consultant Intern. I'm about to finish my Computer Engineering degree, if everything goes well by december I officially will be an engineer. 
  
  Most of my experience has been working with web applications, frameworks like <mark>Flask</mark> or <mark>Electron</mark>. But now at my job I'm learning Java, Docker, Kubernetes, Springboot, AWS. So stay tunned to watch that :)

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: GoGamblerGo
        link: https://github.com/franco-e-s-c/GoGamblerGo-App
        # link_text: Project Website
        additional_links:
          - title: franco-e-s-c/GoGamblerGo-App
            icon: fab fa-github
            url: https://github.com/franco-e-s-c/GoGamblerGo-App
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This was my final project. Me and 2 friends develop this system that bring to machines the classic Iowa Gambling Task, adding some useful features that were asked by a group of Dr's of CUCEI
        description: | # this will include new lines to allow paragraphs
          I highly recommend going through the documentation if you want to undestand this project. It was a full year of development so it's a little complex thing.
      - layout: top-middle
        title: FBref-LigaMx-Scraper
        link: https://github.com/franco-e-s-c/FBref-LigaMx-Scraper
        # link_text: Project Website
        additional_links:
          - title: franco-e-s-c/FBref-LigaMx-Scraper
            icon: fab fa-github
            url: https://github.com/franco-e-s-c/FBref-LigaMx-Scraper
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This was a very little project. I just wanted tu play a little with python and pandas
        description: | # this will include new lines to allow paragraphs
          The objective of this app is create spreadsheets of the LigaMX seasons, incluiding liguilla and regular seasons. All info scrapped from FBref

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: FICO
        link: fico.com
        # link_text: boringcompany.com
        sub_title: Solution Engineering Intern
        caption: July 2024 - Present
        quote: >
          Right now im learning a lot of useful tech and business knowlegde 
        description: | # this will include new lines to allow paragraphs
            I'm just an intern, theres not a lot i have to say. It's been a great experience so far. A bit stressful, but it's my first job so i'm still adapting. I'm glad the team has allowed me to get involved in real project's, i think that's really the best way to experience the real world

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad de Guadalajara. CUCEI
        caption: 2020 - 2024
        sub_title: Computer Engineering
        quote: >
          I'm not a big fan of UDG.
        description: | # this will include new lines to allow paragraphs
          But I had a good university experience, being allowed to knew a lot of people, making good friends, and a lot of contacts too!

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I have free time I like to:
      - Watch Movies & Series
      - Play videogames with my friends
      - Enjoy time with my pets

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
